// 共用的預設追蹤參數清單。
// 同時被 content script、options/popup 頁面（透過 window.defaultParams）
// 以及 background service worker（透過 importScripts，讀 self.defaultParams）使用。
// 使用 globalThis 指派，可在頁面(window)、content script、service worker 三種環境通用。
globalThis.defaultParams = [
  { param: '^utm_', note: '', domain: '' },
  { param: '^stm_', note: '', domain: '' },
  { param: '_gl', note: 'Google Analytics', domain: '' },
  { param: '_ga', note: 'Google Analytics', domain: '' },
  { param: '^__hs', note: 'hubspot', domain: '' },
  { param: '^_hs', note: 'hubspot', domain: '' },
  { param: '^hsa_', note: 'hubspot', domain: '' },
  { param: 'icid', note: '', domain: '' },
  { param: 'igshid', note: '', domain: '' },
  { param: 'ocid', note: '', domain: '' },
  { param: '^mc_', note: '', domain: '' },
  { param: 'mkt_tok', note: '', domain: '' },
  { param: 'fbclid', note: 'facebook', domain: '' },
  { param: 'yclid', note: '', domain: '' },
  { param: '_openstat', note: '', domain: '' },
  { param: 'wicked', note: '', domain: '' },
  { param: 'jobsource', note: '104', domain: '' },
  { param: 'xmt', note: 'Threads', domain: '' },
  { param: 'otc', note: '', domain: '' },
  { param: '^oly_', note: '', domain: '' },
  { param: 'rb_clickid', note: '', domain: '' },
  { param: '^soc_', note: '', domain: '' },
  { param: 'cvid', note: '', domain: '' },
  { param: 'oicd', note: '', domain: '' },
  { param: 'vgo_ee', note: '', domain: '' },
  { param: 'gs_lcrp', note: '', domain: '' },
  { param: 'gclid', note: 'google ads', domain: '' },
  { param: 'gad_source', note: 'google ads', domain: '' },
  { param: 'gad_campaignid', note: 'google ads', domain: '' },
  { param: 'campaignid', note: 'google ads', domain: '' },
  { param: 'adgroupid', note: 'google ads', domain: '' },
  { param: 'gbraid', note: 'google ads', domain: '' },
  { param: 'trackingId', note: '', domain: '' },
  { param: 'srsltid', note: 'google merchant center', domain: '' },
  { param: 'sxsrf', note: 'google search', domain: '' },
  { param: 'gs_lp', note: '', domain: '' },
  { param: 'ved', note: 'google search', domain: '' },
  { param: 'gs_ssp', note: 'google search', domain: '' },
  { param: 'sca_esv', note: 'google search', domain: '' },
  { param: '^ref_', note: 'twitter, google', domain: '' },
  { param: '$deep_link', note: 'reddit', domain: '' },
  { param: '$3p', note: 'reddit', domain: '' },
  { param: 'correlation_id', note: 'reddit', domain: '' },
  { param: 'post_fullname', note: 'reddit', domain: '' },
  { param: '_branch_match_id', note: '', domain: '' },
  { param: '_branch_referrer', note: '', domain: '' },
  { param: 'trk', note: 'linkedin', domain: '' },
  { param: 'mcid', note: '', domain: '' },
  { param: 'upsellOrderOrigin', note: 'linkedin', domain: '' },
  { param: 'referenceId', note: 'linkedin', domain: '' },
  { param: 'miniProfileUrn', note: 'linkedin', domain: '' },
  { param: 'lipi', note: 'linkedin', domain: '' },
  { param: 'trkEmail', note: 'linkedin', domain: '' },
  { param: 'midSig', note: 'linkedin', domain: '' },
  { param: 'midToken', note: 'linkedin', domain: '' },
  { param: 'otpToken', note: 'linkedin', domain: '' },
  { param: 'msclkid', note: '', domain: '' },
  { param: 'rlid', note: '', domain: '' },
  { param: 'fr2', note: 'bing or yahoo', domain: '' },
  { param: 'refId', note: 'bing or yahoo', domain: '' },
  { param: '^attr_', note: 'bing or yahoo', domain: '' },
  { param: '_source_', note: '', domain: '' },
  { param: 'is_from_webapp', note: '', domain: '' },
  { param: 'sender_device', note: '', domain: '' },
  { param: 'adgrpid', note: 'amazon', domain: '' },
  { param: '^hv', note: 'amazon', domain: 'amazon.co' },
  { param: 'hydadcr', note: 'amazon', domain: '' },
  { param: '^pd_rd_', note: 'amazon', domain: '' },
  { param: '^pf_rd_', note: 'amazon', domain: '' },
  { param: 'content-id', note: '', domain: 'amazon.co' },
  { param: 'dib', note: 'amazon', domain: '' },
  { param: 'dib_tag', note: 'amazon', domain: '' },
  { param: 'qid', note: 'amazon', domain: '' },
  { param: 'sp_csd', note: 'amazon', domain: '' },
  { param: 'rh', note: '', domain: 'amazon.co' },
  { param: 'ref', note: '', domain: 'amazon.co' },
  { param: 'rdt_cid', note: '', domain: '' },
  { param: 'li_fat_id', note: 'LinkedIn ad', domain: '' },
  { param: '^highlightedUpdate', note: '', domain: '' },
  { param: 'fingerprint', note: '', domain: '' },
  { param: 'attemptId', note: '', domain: '' },
  { param: 'buvid', note: 'bilibili', domain: '' },
  { param: 'from_spmid', note: 'bilibili', domain: '' },
  { param: '^share_', note: 'bilibili', domain: '' },
  { param: 'spmid', note: 'bilibili', domain: '' },
  { param: 'unique_k', note: 'bilibili', domain: '' },
  { param: 'up_id', note: 'bilibili', domain: '' },
  { param: 'vd_source', note: 'bilibili', domain: '' },
  { param: 'is_story_h5', note: 'bilibili', domain: '' },
  { param: 'mid', note: 'bilibili', domain: '' },
  { param: 'entry-point', note: 'uber', domain: '' },
  { param: 'access-point', note: 'uber', domain: '' },
  { param: 'pass-campaign', note: 'uber', domain: '' },
  { param: '$deeplink_path', note: 'uber', domain: '' },
  { param: 'itmmeta', note: 'ebay', domain: '' },
  { param: 'itmprp', note: 'ebay', domain: '' },
  { param: '_trksid', note: 'ebay', domain: '' },
  { param: 'hash', note: 'ebay', domain: 'ebay.com' },
  { param: 'af_xp', note: '', domain: '' },
  { param: 'shortlink', note: '', domain: '' },
  { param: 'fbid', note: '', domain: '' },
  { param: '^__cft__', note: 'facebook', domain: '' },
  { param: '__tn__', note: 'facebook', domain: '' },
  { param: 'social_share', note: '', domain: '' },
  { param: 'previewDohEventScheduleTesting', note: '', domain: '' },
  { param: 'ecid', note: '', domain: '' },
  { param: 'igsh', note: 'IG', domain: '' },
  { param: '^itm_', note: '', domain: '' }
];

// 前綴參數（^ 開頭）的已知後綴展開表，供 declarativeNetRequest 在「載入前」使用。
// DNR 的 removeParams 只能精確比對參數名，無法做前綴比對，所以這裡把常見的後綴列舉出來。
// 未列到的罕見後綴仍由 content script 在載入後（DOM 改寫 / cleanCurrentPageURL）補清。
globalThis.prefixExpansions = {
  '^utm_': ['utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content', 'utm_id', 'utm_team', 'utm_theme'],
  '^stm_': ['stm_source', 'stm_medium', 'stm_campaign', 'stm_term', 'stm_content'],
  '^__hs': ['__hssc', '__hstc', '__hsfp'],
  '^_hs': ['_hsenc', '_hsmi'],
  '^hsa_': ['hsa_cam', 'hsa_grp', 'hsa_mt', 'hsa_src', 'hsa_ad', 'hsa_acc', 'hsa_net', 'hsa_kw', 'hsa_tgt', 'hsa_ver'],
  '^mc_': ['mc_cid', 'mc_eid'],
  '^oly_': ['oly_anon_id', 'oly_enc_id'],
  '^soc_': ['soc_src', 'soc_trk'],
  '^ref_': ['ref_src', 'ref_url'],
  '^attr_': ['attr_source', 'attr_medium'],
  '^hv': ['hvadid', 'hvpos', 'hvnetw', 'hvrand', 'hvpone', 'hvptwo', 'hvqmt', 'hvdev', 'hvdvcmd', 'hvlocint', 'hvlocphy', 'hvtargid'],
  '^pd_rd_': ['pd_rd_w', 'pd_rd_wg', 'pd_rd_r', 'pd_rd_p', 'pd_rd_i'],
  '^pf_rd_': ['pf_rd_p', 'pf_rd_r', 'pf_rd_s', 'pf_rd_t', 'pf_rd_i', 'pf_rd_m'],
  '^share_': ['share_source', 'share_medium', 'share_plat', 'share_session_id', 'share_tag'],
  '^highlightedUpdate': ['highlightedUpdateUrn'],
  // 注意：^__cft__ 刻意不展開。其實際參數名為 __cft__[0]（含中括號），
  // 非合法的 DNR removeParam 名稱、且在 URL 中常被編碼，硬塞 DNR 不可靠，
  // 故交由 content script 在載入後以 ^ 開頭比對清除。
  '^itm_': ['itm_source', 'itm_medium', 'itm_campaign', 'itm_content', 'itm_term']
};

// 網域限定參數在 DNR 規則中的網域展開。
// content script 用 hostname.includes('amazon.co') 比對（涵蓋 amazon.com / amazon.co.uk…），
// 但 DNR 的 requestDomains 是「網域 + 子網域」精確比對，因此把 amazon 的常見 TLD 列舉出來，
// 才能在 amazon.com 等主要網域上達到「載入前」清除。未列到的網域仍由 content script 補清。
globalThis.domainExpansions = {
  'amazon.co': [
    'amazon.com', 'amazon.co.uk', 'amazon.co.jp', 'amazon.ca', 'amazon.de',
    'amazon.fr', 'amazon.it', 'amazon.es', 'amazon.nl', 'amazon.se',
    'amazon.in', 'amazon.com.au', 'amazon.com.br', 'amazon.com.mx',
    'amazon.com.tr', 'amazon.sg', 'amazon.ae', 'amazon.sa', 'amazon.pl', 'amazon.eg'
  ]
};
